name: run

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '45 7 * * *'

jobs:
  # Build
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Download htmlq
      run: wget -O htmlq.tar.gz https://github.com/mgdm/htmlq/releases/latest/download/htmlq-x86_64-linux.tar.gz 
    - name: Install htmlq
      run: sudo tar xf htmlq.tar.gz -C /usr/local/bin
    - name: Run check
      run: sh run.sh
